const {
    // IMPORTAR CONTROLLERS
  } = require("../controllers/recipeController");
  const { Model1 } = require("../db");


  /*
  ACA DEBEN IR TODOS LOS HANDLERS QUE INVOCAN A LOS CONTROLLERS QUE HACEN LA BUSQUEDA.
  RESPONSABILIDADES:
  EL HANDLER ES QUIEN SE COMUNICA CON LAS ACTIONS DEL FRONT.
  LOS CONTROLLERS SON QUIENES SE COMUNICAN CON LA DATABASE.  
  */

  module.exports = {
   // EXPORTAR HANDLERS
  };