const trades = [  
        {          
          commerceName: "Los hijos de fruta",
          category: "Gastronomía",
          subcategory: "Verdulerias",
          description: "Las verduras frescas de mejor calidad de la zona",
          userName: "verdulagas",
          email: "loshijosdefruta@gmail.com",
          password: "verdu123",
          country: "Argentina",
          city: "Salsipuedes",
          address: "belgrano 1324",
          phone: "03428901929",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo", "Agua de Oro", "Mendiolaza", "El Manzano", "La Granja"],
          productos: [],
          rating: 5,
          epagos: true,
          active: true,
        },
        {          
          commerceName: "Hambur-heros",
          category: "Gastronomía",
          subcategory: "Fast food",
          description:
            "Las mejores promociones en hamburguesas, que incluyen juguetes para los mas chicos",
          userName: "ironburger",
          email: "losaburgers@gmail.com",
          password: "hulkvegano123",
          country: "Colombia",
          city: "Medellin",
          address: "Bolivar 857",
          phone: "08958839219",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo", "Agua de Oro", "Mendiolaza", "El Manzano"],
          productos: [],
          rating: 4,
          epagos: true,
          active: true,
        },
        {          
          commerceName: "La Pizza-Nostra",
          category: "Gastronomía",
          subcategory: "Pizzeria",
          description:
            "Si te contaramos nuestras recetas,no podriamos alimentarte",
          userName: "muzzacorleone",
          email: "vitoycalabresa@gmail.com",
          password: "tonyjamone",
          country: "Uruguay",
          city: "Montevideo",
          address: "Artigas 2563",
          phone: "028575643",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo", "Agua de Oro", "La Granja"],
          productos: [],
          rating: 3,
          epagos: false,
          active: true,
        },
        {          
          commerceName: "El pinar",
          category: "Gastronomía",
          subcategory: "Restaurant",
          description: "Los mejores platos, a delivery y en el lugar",
          userName: "pinito4215",
          email: "araucariasno@gmail.com",
          password: "araucan0s",
          country: "Argentina",
          city: "Posadas",
          address: "Entre Rios 6329",
          phone: "045829394",
          deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza", "El Manzano", "La Granja"],
          productos: [],
          rating: 5,
          epagos: false,
          active: true,
        },
        {          
          commerceName: "Pizzteros",
          category: "Gastronomía",
          subcategory: "Pizzeria",
          description:
            "Si no llega tu pedido en tiempo y forma, te devolvemos la plata",
          userName: "hondaypizza",
          email: "harleypizzason@gmail.com",
          password: "ducatiprovolone",
          country: "Argentina",
          city: "Buenos Aires",
          address: "Rosas",
          phone: "074372894",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Agua de Oro", "Mendiolaza", "El Manzano", "La Granja"],
          productos: [],
          rating: 2,
          epagos: true,
          active: true,
        },            
        {          
          commerceName: "Farmacito",
          category: "Salud",
          subcategory: "Farmacias",
          description: "Los precios mas baratos ante cualquier urgencia",
          userName: "farmaboys",
          email: "farmacito08@gmail.com",
          password: "farma321",
          country: "Paraguay",
          city: "Asuncion",
          address: "Romero 3543",
          phone: "01245009483",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo", "Agua de Oro", "Mendiolaza", "El Manzano", "La Granja"],
          productos: [],
          rating: 5,
          epagos: false,
          active: true,
        },
        {          
          commerceName: "La Muleta Renga",
          category: "Salud",
          subcategory: "Ortopedia",
          description: "Si existe en el rubro, nosotros lo tenemos",
          userName: "Ortorenga",
          email: "Ortorenga@gmail.com",
          password: "orto321",
          country: "Argentina",
          city: "Salsipuedes",
          address: "Romero 3543",
          phone: "01245009483",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo"],
          productos: [],
          rating: 5,
          epagos: false,
          active: true,
        },     
        {          
          commerceName: "Fregadito",
          category: "Hogar",
          subcategory: "Limpieza",
          description: "Los productos para el hogar, al precio mas accesible",
          userName: "lavaditoelmate",
          email: "fregandoporunmañana@gmail.com",
          password: "detergen3",
          country: "Argentina",
          city: "Tucuman",
          address: "Juan Manuel Dorrego 2394",
          phone: "029348510",
          deliveryZone: ["Salsipuedes", "Rio Ceballos", "El Manzano", "La Granja"],
          productos: [],
          rating: 5,
          epagos: false,
          active: true,
        },
        {          
          commerceName: "Tuqui-eres",
          category: "Hogar",
          subcategory: "Bazar",
          description: "Todo lo que buscas para tu hogar, en un solo lugar.",
          userName: "tuquieres",
          email: "tuquieres@gmail.com",
          password: "allbazan",
          country: "Argentina",
          city: "Salsipuedes",
          address: "Juan Manuel Dorrego 2394",
          phone: "029348510",
          deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
          productos: [],
          rating: 3,
          epagos: true,
          active: true,
        }
];

module.exports = {
  trades,
};
