const trades = [
  {
    commerceName: "Los hijos de fruta",
    category: "Gastronomía",
    subcategory: "Verdulerias",
    description: "Las verduras frescas de mejor calidad de la zona",
    image:
      "https://tofuu.getjusto.com/orioneat-prod/dgqKdb6Zfwuqxos5x-20210130_111004.jpg",
    province: "Córdoba",
    city: "Salsipuedes",
    address: "belgrano 1324",
    phone: "03428901929",
    deliveryZone: [
      "Salsipuedes",
      "Rio Ceballos",
      "Unquillo",
      "Agua de Oro",
      "Mendiolaza",
      "El Manzano",
      "La Granja",
    ],
    userName: "verdulagas",
    password: "verdu123",
    email: "loshijosdefruta@gmail.com",
    rating: 5,
    epagos: "Sólo efectivo",
    active: true,
  },
  {
    commerceName: "Deniro",
    category: "Gastronomía",
    subcategory: "Fast food",
    description:
      "Las mejores promociones en hamburguesas, que incluyen juguetes para los mas chicos",
    image:
      "https://centrofranchising.com/wp-content/uploads/2022/02/Screenshot_7.jpg",
    province: "Cordoba",
    city: "Rio Ceballos",
    address: "Bolivar 857",
    phone: "08958839219",
    deliveryZone: [
      "Salsipuedes",
      "Rio Ceballos",
      "Unquillo",
      "Agua de Oro",
      "Mendiolaza",
      "El Manzano",
    ],
    userName: "deniro",
    password: "hulkvegano123",
    email: "deniro@gmail.com",
    rating: 4,
    epagos: "Efectivo/Tarjetas",
    active: true,
  },
  {
    commerceName: "La Pizza-Nostra",
    category: "Gastronomía",
    subcategory: "Pizzeria",
    description: "Si te contaramos nuestras recetas,no podriamos alimentarte",
    image:
      "https://play-lh.googleusercontent.com/s-rbFjuNRuXqNnHM86i3h0OHGjcLZ1xrjVLbkrhB7D8deZkvoKobbijsGYSh49z-qAg=w240-h480-rw",
    province: "Córdoba",
    city: "Agua de Oro",
    address: "Artigas 2563",
    phone: "028575643",
    deliveryZone: [
      "Salsipuedes",
      "Rio Ceballos",
      "Unquillo",
      "Agua de Oro",
      "La Granja",
    ],
    userName: "muzzacorleone",
    password: "tonyjamone",
    email: "vitoycalabresa@gmail.com",
    rating: 3,
    epagos: "Sólo tarjetas",
    active: false,
  },
  {
    commerceName: "El pinar",
    category: "Gastronomía",
    subcategory: "Restaurant",
    description: "Los mejores platos, a delivery y en el lugar",
    image: "https://www.restauranteelpinar.com/img/logo2.png",
    province: "Córdoba",
    city: "Mendiolaza",
    address: "Entre Rios 6329",
    phone: "045829394",
    deliveryZone: [
      "Unquillo",
      "Agua de Oro",
      "Mendiolaza",
      "El Manzano",
      "La Granja",
    ],
    userName: "pinito4215",
    password: "araucan0s",
    email: "araucariasno@gmail.com",
    rating: 5,
    epagos: "Efectivo/Tarjetas",
    active: true,
  },
  {
    commerceName: "Best Pizza",
    category: "Gastronomía",
    subcategory: "Pizzería",
    description:
      "Si no llega tu pedido en tiempo y forma, te devolvemos la plata",
    image:
      "https://www.shutterstock.com/image-vector/bakery-pizzeria-logo-template-smiling-260nw-1076602817.jpg",
    province: "Córdoba",
    city: "El Manzano",
    address: "Rosas 5365",
    phone: "074372894",
    deliveryZone: [
      "Salsipuedes",
      "Rio Ceballos",
      "Agua de Oro",
      "Mendiolaza",
      "El Manzano",
      "La Granja",
    ],
    userName: "hondaypizza",
    password: "ducatiprovolone",
    email: "harleypizzason@gmail.com",
    rating: 2,
    epagos: "Sólo efectivo",
    active: true,
  },
  {
    commerceName: "Farmacia Bozicovich",
    category: "Salud",
    subcategory: "Farmacias",
    description: "Los precios mas baratos ante cualquier urgencia",
    image: "https://www.buscadorcomercial.com.ar/avisos/logo_1004.png",
    province: "Córdoba",
    city: "Unquillo",
    address: "Romero 3543",
    phone: "01245009483",
    deliveryZone: [
      "Salsipuedes",
      "Rio Ceballos",
      "Unquillo",
      "Agua de Oro",
      "Mendiolaza",
      "El Manzano",
      "La Granja",
    ],
    userName: "farmaboys",
    password: "farma321",
    email: "farmacito08@gmail.com",
    rating: 5,
    epagos: "Sólo tarjetas",
    active: true,
  },
  {
    commerceName: "Ortofarma",
    category: "Salud",
    subcategory: "Ortopedia",
    description: "Si existe en el rubro, nosotros lo tenemos",
    image:
      "https://images-platform.99static.com/kJZlHKy06shdh5yqUoE3Ay8u40k=/554x119:1253x818/500x500/top/smart/99designs-contests-attachments/71/71375/attachment_71375817",
    province: "Córdoba",
    city: "Salsipuedes",
    address: "Romero 3543",
    phone: "01245009483",
    deliveryZone: ["Salsipuedes", "Rio Ceballos", "Unquillo"],
    userName: "Ortorenga",
    password: "orto321",
    email: "Ortorenga@gmail.com",
    rating: 5,
    epagos: "Efectivo/Tarjetas",
    active: true,
  },
  {
    commerceName: "Spring Cleaning",
    category: "Hogar",
    subcategory: "Limpieza",
    description: "Los productos para el hogar, al precio mas accesible",
    image: "https://img.freepik.com/vector-gratis/cartel-composicion-diferentes-herramientas-servicio-limpieza-color-vector-fondo-azul_1284-12268.jpg?w=2000",
    province: "Córdoba",
    city: "Tucuman",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Salsipuedes", "Rio Ceballos", "El Manzano", "La Granja"],
    userName: "lavaditoelmate",
    password: "detergen3",
    email: "fregandoporunmañana@gmail.com",
    rating: 5,
    epagos: "Sólo efectivo",
    active: false,
  },
  {
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Fravega",
    category: "Hogar",
    subcategory: "Electrodomesticos",
    description: "Los mejores electrodomesticos para equipar tu hogar",
    image: "https://www.fravega.com/static/logo-fravega@3x.png",
    province: "Misiones",
    city: "Posadas",
    address: "Junin 1939",
    phone: "037281939596",
    deliveryZone: ["Unquillo", "Rosario", "Mendiolaza", "Salsipuedes", "San Juan", "Candelaria", "Eldorado"],
    userName: "Fravega",
    password: "electro123",
    email: "Fravega2001@gmail.com",
    rating: 5,
    epagos: "Efectivo/Tarjetas",
    active: true,
  },{
    commerceName: "Samsung",
    category: "Electronica",
    subcategory: "Celulares",
    description: "Una nueva forma de comunicarse, solo aca",
    image: "https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2018/09/samsung-logo.jpg?tf=3840x",
    province: "Buenos Aires",
    city: "Tigre",
    address: "San Martin 4600",
    phone: "01192848578295",
    deliveryZone: ["La Matanza", "Berazategui", "Ituzaingo","Iguazu", "Apostoles"],
    userName: "Samsung",
    password: "Samñang",
    email: "samsung1976@gmail.com",
    rating: 4,
    epagos: "Sólo Tarjeta",
    active: false,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },{
    commerceName: "Kalen",
    category: "Hogar",
    subcategory: "Bazar",
    description: "Todo lo que buscas para tu hogar, en un solo lugar.",
    image: "https://bazarkalen.com/wp-content/uploads/2021/07/logo-kalen-actualizado-scaled.jpg",
    province: "Córdoba",
    city: "La Granja",
    address: "Juan Manuel Dorrego 2394",
    phone: "029348510",
    deliveryZone: ["Unquillo", "Agua de Oro", "Mendiolaza"],
    userName: "tuquieres",
    password: "allbazan",
    email: "tuquieres@gmail.com",
    rating: 3,
    epagos: "Sólo efectivo",
    active: true,
  },
];

module.exports = {
  trades,
};
